name: mykommunity
version: 1.7.6+76
publish_to: none
description: My Kommunity Resident App
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  awesome_dialog: ^2.2.1
  cached_network_image: ^3.2.1
  firebase: ^9.0.3
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  firebase_messaging: ^11.4.1
  google_fonts: ^3.0.1
  flutter_local_notifications: ^9.6.0
  jiffy: ^5.0.0
  pin_code_fields: ^7.4.0
  flutter_native_splash: ^2.2.0
  email_validator: ^1.0.6
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  device_info: ^2.0.3
  package_info_plus: ^1.4.2
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.4
  loading_overlay: ^0.3.0
  animated_bottom_navigation_bar: ^0.3.3
  carousel_slider: ^4.1.1
  flutter_otp_text_field: ^1.0.1
  flutter_html: ^2.2.1
  xml: ^5.0.0
  flutter_svg: ^0.23.0  
  flutter_launcher_icons: ^0.9.0
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  flutter_share: ^2.0.0
  introduction_screen: ^3.0.2
  country_code_picker: ^2.0.2
  awesome_notifications: ^0.6.21
  image_picker: ^0.8.5+3  
  camera: ^0.9.5
  photo_view: ^0.14.0
  flutter_multi_formatter: ^2.6.0
  styled_text: ^5.1.0
  emoji_picker_flutter: ^1.3.1
  file_picker: ^4.6.0
  firebase_storage: ^10.0.3
  table_calendar: ^2.3.3
  slidable_button: ^2.0.0
  flutter:
    sdk: flutter
  fluent_ui: ^3.12.0
  firedart: ^0.9.0+1
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/images/custom/
    - assets/images/svg/
    - assets/images/buttonimages/
    - assets/images/cities/
    - assets/images/sosimages/
  uses-material-design: true  

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/app_logo.png
  ios: true
  remove_alpha_ios: true
  
flutter_native_splash: 
  background_image: assets/images/splash.png
  fill: false