// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe2LbI7qZ6FEePiW8C6zxvntDMF0Do99U',
    appId: '1:715181243685:web:8bbba60448dd4a5bab6ecc',
    messagingSenderId: '715181243685',
    projectId: 'mykommunity-e1f4e',
    authDomain: 'mykommunity-e1f4e.firebaseapp.com',
    databaseURL: 'https://mykommunity-e1f4e.firebaseio.com',
    storageBucket: 'mykommunity-e1f4e.appspot.com',
    measurementId: 'G-PW10DPF8ZF',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCeQtxcDmQxm5tmqO5bkhfR6HNAYG1uek',
    appId: '1:715181243685:android:cbb3e42ab0d5a7baab6ecc',
    messagingSenderId: '715181243685',
    projectId: 'mykommunity-e1f4e',
    databaseURL: 'https://mykommunity-e1f4e.firebaseio.com',
    storageBucket: 'mykommunity-e1f4e.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXe4-z6dMNs8FIxwOede3y2fgfqTQDYIo',
    appId: '1:715181243685:ios:6ce15e2536cc6ab5ab6ecc',
    messagingSenderId: '715181243685',
    projectId: 'mykommunity-e1f4e',
    databaseURL: 'https://mykommunity-e1f4e.firebaseio.com',
    storageBucket: 'mykommunity-e1f4e.appspot.com',
    androidClientId: '715181243685-645sfeu8eqneibr6d43avlk8rvjb54s3.apps.googleusercontent.com',
    iosClientId: '715181243685-itefum55gl4j2h7jofk2u913i6mfhtse.apps.googleusercontent.com',
    iosBundleId: 'com.mohrisa.mykommunity',
  );
}
